[tool.black]
line-length = 127
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | build
  | dist
  | old_finger_gun_examples
)/
'''

[tool.isort]
profile = "black"
line_length = 127
skip_gitignore = true
skip = ["venv", ".venv", "env", "old_finger_gun_examples"]
known_first_party = ["src", "game", "screens", "utils"]
known_third_party = ["pygame", "cv2", "mediapipe", "numpy"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
import_heading_stdlib = "Standard library imports"
import_heading_thirdparty = "Third-party imports"
import_heading_firstparty = "Local application imports"


[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv", "env", "old_finger_gun_examples"]
skips = ["B101"]  # Skip assert_used test

[tool.pip-audit]
ignore-vulns = []
require-hashes = false